'use client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthProvider from './context/AuthProvider';
import ToasterContext from './context/ToasterContext';
import { signOut } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Fuel Quote Predictor Group 6',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {/* <button
            className="butoon"
            onClick={() => signOut({ callbackUrl: 'http://localhost:3000' })}
          >
            Sign Out
          </button> */}
          <ToasterContext />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
